# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diagnosticreport.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='diagnosticreport.proto',
  package='diagnosticreport',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x64iagnosticreport.proto\x12\x10\x64iagnosticreport\"%\n\x04\x46ile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"*\n\nFileLength\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\"D\n\rCommandOutput\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x12\n\nstatusCode\x18\x03 \x01(\x05\"1\n\x0bUnknownPair\x12\x10\n\x08unknown1\x18\x01 \x01(\t\x12\x10\n\x08unknown2\x18\x02 \x01(\t\"\xf9\x02\n\x10\x44iagnosticReport\x12\x0f\n\x07version\x18\x01 \x01(\t\x12%\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x16.diagnosticreport.File\x12\x14\n\x0cstormVersion\x18\x03 \x01(\t\x12\x18\n\x10whirlwindVersion\x18\x04 \x01(\t\x12\x15\n\rnetworkConfig\x18\x05 \x01(\t\x12\x31\n\x0b\x66ileLengths\x18\x07 \x03(\x0b\x32\x1c.diagnosticreport.FileLength\x12\x0f\n\x07wanInfo\x18\x08 \x01(\t\x12\x37\n\x0e\x63ommandOutputs\x18\t \x03(\x0b\x32\x1f.diagnosticreport.CommandOutput\x12\x10\n\x08infoJSON\x18\n \x01(\t\x12\x10\n\x08unknown1\x18\x0b \x01(\x05\x12\x33\n\x0cunknownPairs\x18\x0c \x03(\x0b\x32\x1d.diagnosticreport.UnknownPair\x12\x10\n\x08unixTime\x18\r \x01(\x05\x62\x06proto3')
)




_FILE = _descriptor.Descriptor(
  name='File',
  full_name='diagnosticreport.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='diagnosticreport.File.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='diagnosticreport.File.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=81,
)


_FILELENGTH = _descriptor.Descriptor(
  name='FileLength',
  full_name='diagnosticreport.FileLength',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='diagnosticreport.FileLength.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='diagnosticreport.FileLength.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=125,
)


_COMMANDOUTPUT = _descriptor.Descriptor(
  name='CommandOutput',
  full_name='diagnosticreport.CommandOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='diagnosticreport.CommandOutput.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output', full_name='diagnosticreport.CommandOutput.output', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='diagnosticreport.CommandOutput.statusCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=195,
)


_UNKNOWNPAIR = _descriptor.Descriptor(
  name='UnknownPair',
  full_name='diagnosticreport.UnknownPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='diagnosticreport.UnknownPair.unknown1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown2', full_name='diagnosticreport.UnknownPair.unknown2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=246,
)


_DIAGNOSTICREPORT = _descriptor.Descriptor(
  name='DiagnosticReport',
  full_name='diagnosticreport.DiagnosticReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='diagnosticreport.DiagnosticReport.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='files', full_name='diagnosticreport.DiagnosticReport.files', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stormVersion', full_name='diagnosticreport.DiagnosticReport.stormVersion', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='whirlwindVersion', full_name='diagnosticreport.DiagnosticReport.whirlwindVersion', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='networkConfig', full_name='diagnosticreport.DiagnosticReport.networkConfig', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fileLengths', full_name='diagnosticreport.DiagnosticReport.fileLengths', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wanInfo', full_name='diagnosticreport.DiagnosticReport.wanInfo', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commandOutputs', full_name='diagnosticreport.DiagnosticReport.commandOutputs', index=7,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='infoJSON', full_name='diagnosticreport.DiagnosticReport.infoJSON', index=8,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='diagnosticreport.DiagnosticReport.unknown1', index=9,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknownPairs', full_name='diagnosticreport.DiagnosticReport.unknownPairs', index=10,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unixTime', full_name='diagnosticreport.DiagnosticReport.unixTime', index=11,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=626,
)

_DIAGNOSTICREPORT.fields_by_name['files'].message_type = _FILE
_DIAGNOSTICREPORT.fields_by_name['fileLengths'].message_type = _FILELENGTH
_DIAGNOSTICREPORT.fields_by_name['commandOutputs'].message_type = _COMMANDOUTPUT
_DIAGNOSTICREPORT.fields_by_name['unknownPairs'].message_type = _UNKNOWNPAIR
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['FileLength'] = _FILELENGTH
DESCRIPTOR.message_types_by_name['CommandOutput'] = _COMMANDOUTPUT
DESCRIPTOR.message_types_by_name['UnknownPair'] = _UNKNOWNPAIR
DESCRIPTOR.message_types_by_name['DiagnosticReport'] = _DIAGNOSTICREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'diagnosticreport_pb2'
  # @@protoc_insertion_point(class_scope:diagnosticreport.File)
  ))
_sym_db.RegisterMessage(File)

FileLength = _reflection.GeneratedProtocolMessageType('FileLength', (_message.Message,), dict(
  DESCRIPTOR = _FILELENGTH,
  __module__ = 'diagnosticreport_pb2'
  # @@protoc_insertion_point(class_scope:diagnosticreport.FileLength)
  ))
_sym_db.RegisterMessage(FileLength)

CommandOutput = _reflection.GeneratedProtocolMessageType('CommandOutput', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDOUTPUT,
  __module__ = 'diagnosticreport_pb2'
  # @@protoc_insertion_point(class_scope:diagnosticreport.CommandOutput)
  ))
_sym_db.RegisterMessage(CommandOutput)

UnknownPair = _reflection.GeneratedProtocolMessageType('UnknownPair', (_message.Message,), dict(
  DESCRIPTOR = _UNKNOWNPAIR,
  __module__ = 'diagnosticreport_pb2'
  # @@protoc_insertion_point(class_scope:diagnosticreport.UnknownPair)
  ))
_sym_db.RegisterMessage(UnknownPair)

DiagnosticReport = _reflection.GeneratedProtocolMessageType('DiagnosticReport', (_message.Message,), dict(
  DESCRIPTOR = _DIAGNOSTICREPORT,
  __module__ = 'diagnosticreport_pb2'
  # @@protoc_insertion_point(class_scope:diagnosticreport.DiagnosticReport)
  ))
_sym_db.RegisterMessage(DiagnosticReport)


# @@protoc_insertion_point(module_scope)
